### ISSUE TITLE
MacOS Apple Silicon Precompilation Error

### ISSUE THREAD

**Issue by storopoli** [JuliaBooks/Books.jl#309]
I am getting this error when trying to add `Books.jl` in a fresh environment:

```julia
pkg> precompile
Precompiling project...
  ✗ Books
  0 dependencies successfully precompiled in 3 seconds. 88 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Books [939d5c6b-51ae-42e7-97ca-7564d0d4ad91]

Failed to precompile Books [939d5c6b-51ae-42e7-97ca-7564d0d4ad91] to /Users/storopoli/.julia/compiled/v1.8/Books/jl_Wh6Qsr.
ERROR: LoadError: UndefVarError: pandoc_crossref_path not defined
Stacktrace:
 [1] include
   @ ./Base.jl:419 [inlined]
 [2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [3] top-level scope
   @ stdin:1
in expression starting at /Users/storopoli/.julia/packages/Books/8Xi9l/src/Books.jl:1
in expression starting at stdin:1

```

**Comment by lazarusA** [comment]
ahhh, same here, but close, https://github.com/JuliaBooks/Books.jl/issues/307 take a look.

**Comment by kahaaga** [comment]
I also have the identical problem on a MacBook Air (M1, 2020; MacOS Monterey). Fresh julia environment, identical error message to the above. I could not resolve the issue by opening Julia with Rosetta, as hinted at in #307.

If anyone has step-by-step instructions to make this work on an M1-mac, using any some of workaround, it would be greatly appreciated.

**Comment by lazarusA** [comment]
@kahaaga deleting first completely your ~./julia  directory and then installing Julia for macOS x86 (Intel or Rosetta) did work for me. I needed to get rid-off of some corruptions in the scratchspaces folder, and just to be sure I nuked the whole folder.

**Comment by kahaaga** [comment]
@lazarusA Thank you so much! With a slight modification, that did the trick. For anyone else seeing this, what worked for me was

1. Completely uninstalling all Julia versions on my system.
2. Deleting the `~./julia` folder.
3. Downloading and installing, as suggested by @lazarusA, Julia [macOS x86](https://julialang.org/downloads/).
4. Open `Julia` again (which should now automatically open in Rosetta; you can verify this by right-clicking the julia icon in the Applications folder and select "get info")
5. Run `using Pkg; Pkg.install("Books"); using Books`.

For some reason, without step 1, I kept getting the same error. I don't understand why. Anyways, following the steps above, it now works.

**Comment by storopoli** [comment]
I think this should be fixed with [`JuliaBinaryWrappers/pandoc_crossref_jll.jl`](https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl) being built for `aarch64-apple-darwin`.

Related: https://github.com/JuliaPackaging/Yggdrasil/issues/2763

**Comment by ivaquero** [comment]
The problem remains, because `pandoc_crossref_jll.jl` started to support `aarch64-apple-darwin` since `v0.3.12+0`, but `Books.jl`'s dependency is `v0.3.9+0`.
